venv=${VIRTUAL_ENV}
python=${venv}/Scripts/python.exe
python=python

.DEFAULT: test

.PHONY: install check generate test

install:
	pip install -r requirements.txt

check:
	textx check grammar/archimate.tx

generate:
	- rm grammar/archimate.dot
	textx generate grammar/archimate.tx --target dot
	dot -Tpng grammar/archimate.dot > archimate.png

test: check generate
	${python} ./ArchDown.py	
